export PYTHONPATH=~/Dropbox/workspace:~/Dropbox/workspace/SVAS/scripts
data_dir=~/Desktop/HXLC_sv_data

sv_gene_fns=/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC001T/LC001T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC002T/LC002T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC003T/LC003T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC004T/LC004T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC005T/LC005T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC006T/LC006T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC007T/LC007T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC008T/LC008T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC009T/LC009T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC012T/LC012T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC013T/LC013T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC014T/LC014T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC015T/LC015T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC016T/LC016T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC017T/LC017T_sv_gene.csv,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC018T/LC018T_sv_gene.csv
sv_fns=/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC001T/LC001T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC002T/LC002T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC003T/LC003T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC004T/LC004T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC005T/LC005T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC006T/LC006T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC007T/LC007T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC008T/LC008T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC009T/LC009T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC012T/LC012T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC013T/LC013T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC014T/LC014T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC015T/LC015T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC016T/LC016T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC017T/LC017T.sv.txt,/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data/LC018T/LC018T.sv.txt

python3 scOncoprint.py call \
    --sv_gene_fns=$sv_gene_fns \
    --sv_fns=$sv_fns \
    --sample_fn=/Users/chenlingxi/Dropbox/workspace/HXLC/huaxi_meta_sample.csv \
    --out_dir=/Users/chenlingxi/Dropbox/workspace/HXLC/sv_data \
    --target_gene_fn=/Users/chenlingxi/Dropbox/workspace/HXLC/sv/sv_indel_target_pathway_genes.txt
